"""contracts —— 冻结契约的唯一包内出口。

tools/agent/web 各层只从这里 import 契约类型，不直接碰文件路径。
"""

from wagent_backend.ops.contracts.enums import (
    ALWAYS_PALLIATIVE,
    CURATIVE_ACTIONS,
    DEFAULT_LIABILITY,
    SAFETY_PRECHECK_KEYWORDS,
    SYMPTOM_CANDIDATE_CAUSES,  # noqa: F401  （再导出保持完整；agent 层禁用，见 prompts.py）
    ActionEnum,
    LiabilityEnum,
    RootCauseEnum,
    SymptomEnum,
)
from wagent_backend.ops.contracts.schemas import (
    TOOL_REGISTRY,
    Asset,
    AssetRuntime,
    CreateWorkorderInput,
    CreateWorkorderOutput,
    Decision,
    EscalateToHumanInput,
    EscalateToHumanOutput,
    FindTechnicianInput,
    FindTechnicianOutput,
    GetAssetsServingSpaceInput,
    GetAssetsServingSpaceOutput,
    JudgeLiabilityInput,
    JudgeLiabilityOutput,
    MemoryItem,
    NotifyInput,
    NotifyOutput,
    QueryWorkorderHistoryInput,
    QueryWorkorderHistoryOutput,
    RecallMemoryInput,
    RecallMemoryOutput,
    ResolveSpaceInput,
    ResolveSpaceOutput,
    SpaceMatch,
    Technician,
    ToolError,
    VerifyMemoryPredictionInput,
    VerifyMemoryPredictionOutput,
    WorkOrder,
    WorkOrderDisposition,
    WriteMemoryInput,
    WriteMemoryOutput,
)

__all__ = [
    "ALWAYS_PALLIATIVE",
    "CURATIVE_ACTIONS",
    "DEFAULT_LIABILITY",
    "SAFETY_PRECHECK_KEYWORDS",
    "SYMPTOM_CANDIDATE_CAUSES",
    "ActionEnum",
    "LiabilityEnum",
    "RootCauseEnum",
    "SymptomEnum",
    "TOOL_REGISTRY",
    "Asset",
    "AssetRuntime",
    "CreateWorkorderInput",
    "CreateWorkorderOutput",
    "Decision",
    "EscalateToHumanInput",
    "EscalateToHumanOutput",
    "FindTechnicianInput",
    "FindTechnicianOutput",
    "GetAssetsServingSpaceInput",
    "GetAssetsServingSpaceOutput",
    "JudgeLiabilityInput",
    "JudgeLiabilityOutput",
    "MemoryItem",
    "NotifyInput",
    "NotifyOutput",
    "QueryWorkorderHistoryInput",
    "QueryWorkorderHistoryOutput",
    "RecallMemoryInput",
    "RecallMemoryOutput",
    "ResolveSpaceInput",
    "ResolveSpaceOutput",
    "SpaceMatch",
    "Technician",
    "ToolError",
    "VerifyMemoryPredictionInput",
    "VerifyMemoryPredictionOutput",
    "WorkOrder",
    "WorkOrderDisposition",
    "WriteMemoryInput",
    "WriteMemoryOutput",
]
